import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";

const config: Config = {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				"neutral-900": "var(--neutral-900)",
				"neutral-800": "var(--neutral-800)",
				"neutral-700": "var(--neutral-700)",
				"neutral-600": "var(--neutral-600)",
				"neutral-500": "var(--neutral-500)",
				"neutral-400": "var(--neutral-400)",
				"neutral-300": "var(--neutral-300)",
				"neutral-200": "var(--neutral-200)",
				"neutral-100": "var(--neutral-100)",
				"neutral-50": "var(--neutral-50)",
				"neutral-0": "var(--neutral-0)",
				primary: "var(--primary)",
				"primary-hover": "var(--primary-hover)",
				"primary-active": "var(--primary-active)",
				"primary-subtle": "var(--primary-subtle)",
				"primary-soft": "var(--primary-soft)",
				secondary: "var(--secondary)",
				"secondary-hover": "var(--secondary-hover)",
				"secondary-active": "var(--secondary-active)",
				"secondary-subtle": "var(--secondary-subtle)",
				"secondary-soft": "var(--secondary-soft)",
			},
			fontFamily: {
				hero: ["var(--font-hero)"],
				title: ["var(--font-title)"],
				subtitle: ["var(--font-subtitle)"],
				label: ["var(--font-label)"],
				body: ["var(--font-body)"],
				data: ["var(--font-data)"],
			},
		},
	},
	plugins: [
		plugin(({ addUtilities }) => {
			addUtilities({
				".text-hero-small": {
					fontFamily: "var(--font-hero)",
					fontWeight: "700",
					fontSize: "var(--hero-small)",
					lineHeight: "80px",
					letterSpacing: "0",
				},
				".text-hero-regular": {
					fontFamily: "var(--font-hero)",
					fontWeight: "700",
					fontSize: "var(--hero-regular)",
					lineHeight: "95px",
					letterSpacing: "0",
				},
				".text-hero-large": {
					fontFamily: "var(--font-hero)",
					fontWeight: "700",
					fontSize: "var(--hero-large)",
					lineHeight: "105px",
					letterSpacing: "0",
				},
				".text-title-small": {
					fontFamily: "var(--font-title)",
					fontWeight: "700",
					fontSize: "var(--title-small)",
					lineHeight: "70px",
					letterSpacing: "-0.02em",
				},
				".text-title-regular": {
					fontFamily: "var(--font-title)",
					fontWeight: "700",
					fontSize: "var(--title-regular)",
					lineHeight: "85px",
					letterSpacing: "-0.02em",
				},
				".text-title-large": {
					fontFamily: "var(--font-title)",
					fontWeight: "700",
					fontSize: "var(--title-large)",
					lineHeight: "110px",
					letterSpacing: "-0.02em",
				},
				".text-subtitle-small": {
					fontFamily: "var(--font-subtitle)",
					fontWeight: "600",
					fontSize: "var(--subtitle-small)",
					lineHeight: "22px",
					letterSpacing: "-0.02em",
				},
				".text-subtitle-regular": {
					fontFamily: "var(--font-subtitle)",
					fontWeight: "600",
					fontSize: "var(--subtitle-regular)",
					lineHeight: "32px",
					letterSpacing: "-0.02em",
				},
				".text-subtitle-large": {
					fontFamily: "var(--font-subtitle)",
					fontWeight: "600",
					fontSize: "var(--subtitle-large)",
					lineHeight: "45px",
					letterSpacing: "-0.02em",
				},
				".text-subtitle-extra-large": {
					fontFamily: "var(--font-subtitle)",
					fontWeight: "600",
					fontSize: "var(--subtitle-extra-large)",
					lineHeight: "60px",
					letterSpacing: "-0.02em",
				},
				".text-body-small": {
					fontFamily: "var(--font-body)",
					fontWeight: "400",
					fontSize: "var(--body-small)",
					lineHeight: "17px",
					letterSpacing: "-0.02em",
				},
				".text-body-regular": {
					fontFamily: "var(--font-body)",
					fontWeight: "400",
					fontSize: "var(--body-regular)",
					lineHeight: "18px",
					letterSpacing: "-0.02em",
				},
				".text-body-large": {
					fontFamily: "var(--font-body)",
					fontWeight: "400",
					fontSize: "var(--body-large)",
					lineHeight: "23px",
					letterSpacing: "-0.02em",
				},
				".text-body-extra-large": {
					fontFamily: "var(--font-body)",
					fontWeight: "400",
					fontSize: "var(--body-extra-large)",
					lineHeight: "28px",
					letterSpacing: "-0.02em",
				},
				".text-data-small": {
					fontFamily: "var(--font-data)",
					fontWeight: "400",
					fontSize: "var(--data-small)",
					lineHeight: "14px",
					letterSpacing: "0",
				},
				".text-data-regular": {
					fontFamily: "var(--font-data)",
					fontWeight: "400",
					fontSize: "var(--data-regular)",
					lineHeight: "14px",
					letterSpacing: "0",
				},
				".text-label-small": {
					fontFamily: "var(--font-label)",
					fontWeight: "500",
					fontSize: "var(--label-small)",
					lineHeight: "22px",
					letterSpacing: "-0.02em",
				},
				".text-label-regular": {
					fontFamily: "var(--font-label)",
					fontWeight: "500",
					fontSize: "var(--label-regular)",
					lineHeight: "26px",
					letterSpacing: "-0.02em",
				},
				".text-label-large": {
					fontFamily: "var(--font-label)",
					fontWeight: "500",
					fontSize: "var(--label-large)",
					lineHeight: "28px",
					letterSpacing: "-0.02em",
				},
			});
		}),
	],
};

export default config;
